export const topics = [
  "Hash Map",
  "DP",
  "Math",
  "Sorting",
  "Greedy",
  "DFS",
  "BFS",
  "Binary Search",
  "Prefix Sum",
  "Partial Sum",
  "Tree",
  "Graph",
  "Matrix",
  "Two Pointers",
  "Bits",
  "Stack",
  "Queue",
  "Heap",
  "Linked List",
  "Backtracking",
  "Sliding Window",
  "Union Find",
  "Trie",
  "Recursion",
  "Simulation",
  "DNC",
  "Topological Sort",
  "Bitmask",
  "Geometry",
  "Segment Tree",
  "Binary Indexed Tree",
  "Number Theory",
  "Game Theory",
  "String Matching",
  "Shortest Path",
  "Combinatorics",
  "Probability",
  "Implementation",
  "Data Structures",
  "Brute Force",
  "Constructive Algorithms",
  "Interactive",
  "Hashing",
  "Flow",
  "Design",
  "Observation",
  "Contribution Technique",
]; 